"""change in chat_session

Revision ID: 0050c80e7c5c
Revises: e8152ac7ade4
Create Date: 2026-07-30 19:12:26.345541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0050c80e7c5c'
down_revision: Union[str, Sequence[str], None] = 'e8152ac7ade4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('dataset_uid', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_chat_sessions_datast_uid'), table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_dataset_uid'), 'chat_sessions', ['dataset_uid'], unique=False)
    op.drop_constraint(op.f('chat_sessions_datast_uid_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'datasets', ['dataset_uid'], ['uid'])
    op.drop_column('chat_sessions', 'datast_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('datast_uid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_datast_uid_fkey'), 'chat_sessions', 'datasets', ['datast_uid'], ['uid'])
    op.drop_index(op.f('ix_chat_sessions_dataset_uid'), table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_datast_uid'), 'chat_sessions', ['datast_uid'], unique=False)
    op.drop_column('chat_sessions', 'dataset_uid')
    # ### end Alembic commands ###
