"""initial change

Revision ID: 2191c24f8b34
Revises: 
Create Date: 2026-07-28 19:30:24.000381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2191c24f8b34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_accounts',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('datasets',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('owner_uid', sa.UUID(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stored_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='datasetstatus'), nullable=False),
    sa.Column('equipment_count', sa.Integer(), nullable=True),
    sa.Column('average_flowrate', sa.Float(), nullable=True),
    sa.Column('average_pressure', sa.Float(), nullable=True),
    sa.Column('average_temperature', sa.Float(), nullable=True),
    sa.Column('min_flowrate', sa.Float(), nullable=True),
    sa.Column('max_flowrate', sa.Float(), nullable=True),
    sa.Column('min_pressure', sa.Float(), nullable=True),
    sa.Column('max_pressure', sa.Float(), nullable=True),
    sa.Column('min_temperature', sa.Float(), nullable=True),
    sa.Column('max_temperature', sa.Float(), nullable=True),
    sa.Column('equipment_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inactive_equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['owner_uid'], ['user_accounts.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('equipment',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('dataset_uid', sa.UUID(), nullable=False),
    sa.Column('equipment_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('equipment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('flowrate', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_uid'], ['datasets.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_equipment_uid'), 'equipment', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_uid'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_table('datasets')
    op.drop_table('user_accounts')
    # ### end Alembic commands ###
