"""add chat type

Revision ID: 33241b606008
Revises: f9c70148ae1d
Create Date: 2026-07-31 16:15:04.923645

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '33241b606008'
down_revision: Union[str, Sequence[str], None] = 'f9c70148ae1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

chat_type_enum = postgresql.ENUM(
    "SQL",
    "RAG",
    name="chattype"
)


def upgrade():
    # Create enum type
    chat_type_enum.create(op.get_bind(), checkfirst=True)

    # Add column
    op.add_column(
        "chat_sessions",
        sa.Column(
            "chat_type",
            chat_type_enum,
            nullable=False,
            server_default="SQL"
        )
    )

    # Remove default after populating existing rows
    op.alter_column(
        "chat_sessions",
        "chat_type",
        server_default=None
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'chat_type')
    chat_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
