"""change in document table

Revision ID: 7d1c0f90b2ed
Revises: 8ac606ac81ba
Create Date: 2026-07-30 00:04:22.092629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d1c0f90b2ed'
down_revision: Union[str, Sequence[str], None] = '8ac606ac81ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('owner_uid', sa.Uuid(), nullable=False))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_documents_owner_uid'), 'documents', ['owner_uid'], unique=False)
    op.drop_constraint(op.f('documents_uploaded_by_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'user_accounts', ['owner_uid'], ['uid'])
    op.drop_column('documents', 'uploaded_by')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_uploaded_by_fkey'), 'documents', 'user_accounts', ['uploaded_by'], ['uid'])
    op.drop_index(op.f('ix_documents_owner_uid'), table_name='documents')
    op.alter_column('documents', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('documents', 'owner_uid')
    # ### end Alembic commands ###
