"""create chat session tables

Revision ID: 8dd3bd3ee956
Revises: 2191c24f8b34
Create Date: 2026-07-29 00:19:00.819081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8dd3bd3ee956'
down_revision: Union[str, Sequence[str], None] = '2191c24f8b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('owner_uid', sa.Uuid(), nullable=False),
    sa.Column('datast_uid', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['datast_uid'], ['datasets.uid'], ),
    sa.ForeignKeyConstraint(['owner_uid'], ['user_accounts.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_chat_sessions_datast_uid'), 'chat_sessions', ['datast_uid'], unique=False)
    op.create_index(op.f('ix_chat_sessions_owner_uid'), 'chat_sessions', ['owner_uid'], unique=False)
    op.create_index(op.f('ix_chat_sessions_uid'), 'chat_sessions', ['uid'], unique=False)
    op.create_table('chat_messages',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('session_uid', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('User', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_uid'], ['chat_sessions.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_chat_messages_session_uid'), 'chat_messages', ['session_uid'], unique=False)
    op.create_unique_constraint(None, 'datasets', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datasets', type_='unique')
    op.drop_index(op.f('ix_chat_messages_session_uid'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_uid'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_owner_uid'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_datast_uid'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
