"""chage in user table

Revision ID: de57963aeed0
Revises: 33241b606008
Create Date: 2026-08-01 11:08:12.349991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de57963aeed0'
down_revision: Union[str, Sequence[str], None] = '33241b606008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_sessions_owner_uid_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'user_accounts', ['owner_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_owner_uid_fkey'), 'chat_sessions', 'user_accounts', ['owner_uid'], ['uid'])
    # ### end Alembic commands ###
