"""change in relationship

Revision ID: f9c70148ae1d
Revises: 0050c80e7c5c
Create Date: 2026-07-30 19:51:56.852511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f9c70148ae1d'
down_revision: Union[str, Sequence[str], None] = '0050c80e7c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_sessions_dataset_uid_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'datasets', ['dataset_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_dataset_uid_fkey'), 'chat_sessions', 'datasets', ['dataset_uid'], ['uid'])
    # ### end Alembic commands ###
